### ISSUE TITLE
Issue when npm run build

### ISSUE THREAD

**Issue by leilaylp** [gianlucacandiotti/laravue#4]
Hi, I followed every step from the readme.md and when I ran the` npm run build` command I had the following problem:
![screenshot from 2016-10-20 16-28-42](https://cloud.githubusercontent.com/assets/11009648/19578652/4d962324-96e2-11e6-9ddd-ccf82bd81574.png)
I am using vagrant and homestead just in case.

**Comment by gianlucacandiotti** [comment]
I merged your fix. Thank you for your time !

Just in case anyone reviews this, it was a problem with the reference to the script inside the package.json. A letter wasn't uppercased correctly and some systems didn't catch the error.
